version: "3.9"
services:
  main:
    build: deploy
    container_name: freebooksapi
    ports:
      - "80:80"
    volumes:
      - /root/..freebooksapi-data
    environment:
      - RUNNER_DISHOOK_URL