version: "3.9"
services:
  main:
    build:
      context: .
      target: deploy
    container_name: freebooksapi
    ports:
      - "8000:8000"
    volumes:
      - /root/..freebooksapi-data
    environment:
      - RUNNER_DISHOOK_URL