name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          RUNNER_DISHOOK_URL: ${{ secrets.RUNNER_DISHOOK_URL }}

      - name: Cleanup Unused Images
        run: docker image prune -f
